### ISSUE TITLE
Using @types/node version below 10，will report an error!

### ISSUE THREAD

**Issue by inX95** [node-modules/utility#49]
node_modules/utility/index.d.ts(460,13): error TS2694: Namespace 'NodeJS' has no exported member 'Immediate'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2

------- 
using Typescript with @types/node@9 and lower version，utility can't be run ok! Because NodeJS.Immediate is added in [DefinitelyTyped/node/v10](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6a3064cc7408b4e71d0d0feb6f92457d4c22e15c/types/node/v10/globals.d.ts)

**Comment by inX95** [comment]
![image](https://user-images.githubusercontent.com/9266048/62854416-df557180-bd21-11e9-8918-ecafa51743d8.png)

**Comment by fengmk2** [comment]
closes by https://github.com/node-modules/utility/pull/60
