### ISSUE TITLE
Error: Unable to resolve module `assert` from `node_modules\utility\lib\function.js`

### ISSUE THREAD

**Issue by cjfpersonal** [node-modules/utility#53]
Error: Unable to resolve module `assert` from `node_modules\utility\lib\function.js`
![image](https://user-images.githubusercontent.com/17400972/72710225-92fc4080-3ba1-11ea-95ff-dbe2ca542938.png)
is it support app?

**Comment by dead-horse** [comment]
sorry, this module is design for node.js and not support other runtime.
